language: viml

sudo: required
dist: trusty

os:
  - linux
  - osx

osx_image: xcode7.3

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install macvim --with-override-system-vim; fi
  - vim --version
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone https://github.com/thinca/vim-themis
# TODO: WORKARROUND: vimspec before all bug
  - cd vim-themis
  - git reset --hard 17b0910d7da5ae3e5a3755470b71a00f1f755163

script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v autoload plugin
  - vim-themis/bin/themis
